import { Inter } from 'next/font/google'
import './globals.css'
import Toasterrr from '@/components/Toaster'
import SessionProviderr from '@/controllers/SessionProviderr'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <SessionProviderr>
      <html lang="en">
        <Toasterrr />
        <body className={inter.className}>{children}</body>
      </html>
    </SessionProviderr>
  )
}
